spring:
  application:
    name:                       Spring boot

  datasource:
    driver-class-name:          org.h2.Driver
    url:                        jdbc:h2:~/test
    username:

  jpa:
    properties:
      hibernate:
        dialect:                org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          schema-generation:
            database:
              # the action values: none, create, drop-and-create, drop
              action:           drop-and-create
            scripts:
              action:           drop-and-create
              create-target:    ./db/create.sql
              drop-target:      ./db/drop.sql
    show-sql:                   false
server:
  port: 9090
  context-path: /calendar

info:
  app:
    name:               Event planner
    description:        Event planner Application
    version:            0.1.0-SNAPSHOT
  developers:
      - name:               Antonel Ernest Pazargic
        email:              antonel.pazargic@gmail.com
      - name:               Irina Stan
        email:              irina.stan@gmail.com

management:
  port:                 9091
  context-path:         /management
endpoints:
  actuator:
    enabled: true
    sensitive: false
  mappings:
    sensitive: false
  beans:
    sensitive: false
